import type { Metadata } from "next";
import { Jua, Work_Sans, Advent_Pro } from "next/font/google";
import "./globals.css";

export const jua = Jua({weight: '400', preload: false});
export const advent = Advent_Pro({weight: '400', preload: false})
export const wsans = Work_Sans({weight: '400', preload: false})

export const metadata: Metadata = {
  title: "Aniziga",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={wsans.className}>{children}</body>
    </html>
  );
}
